import Link from "next/link";
import { exploreCandidates,exploreOptions } from "@/lib/platform/discovery";
import { PageHeader } from "@/components/shell/shell-context";
export const dynamic="force-dynamic";
export default async function ExplorePage({searchParams}:PageProps<"/explorar">){
 const sp=await searchParams;const value=(key:string)=>typeof sp[key]==="string"?sp[key] as string:"";const year=Number(value("ano"))||undefined;
 const options=exploreOptions();const result=exploreCandidates({q:value("q"),year,state:value("uf"),office:value("cargo"),city:value("cidade"),page:Number(value("page"))});
 const previous=new URLSearchParams(Object.entries(sp).filter((entry):entry is [string,string]=>typeof entry[1]==="string"));previous.set("page",String(result.page-1));
 const next=new URLSearchParams(Object.entries(sp).filter((entry):entry is [string,string]=>typeof entry[1]==="string"));next.set("page",String(result.page+1));
 return <main className="platform-page"><PageHeader group="Consulta local" current="Minha cidade e candidaturas"/><h1>Conheça as candidaturas da sua região</h1><p>Escolha eleição, estado, cargo e município. Para cargos estaduais ou nacionais, o registro de candidatura pode indicar a unidade eleitoral em vez de um município.</p><form className="platform-form" action="/explorar"><label>Nome ou nome de urna<input name="q" defaultValue={value("q")}/></label><label>Eleição<select name="ano" defaultValue={value("ano")}><option value="">Todas</option>{options.years.map(y=><option key={y}>{y}</option>)}</select></label><label>Estado<select name="uf" defaultValue={value("uf")}><option value="">Todos</option>{options.states.map(s=><option key={s}>{s}</option>)}</select></label><label>Cargo<select name="cargo" defaultValue={value("cargo")}><option value="">Todos</option>{options.offices.map(s=><option key={s}>{s}</option>)}</select></label><label>Município ou unidade eleitoral<input name="cidade" defaultValue={value("cidade")}/></label><button className="btn" type="submit">Explorar</button></form><p>{result.total.toLocaleString("pt-BR")} pessoas encontradas · página {result.page}</p><div className="platform-grid">{result.rows.map(row=><article className="card" key={row.personId}><Link className="link-primary font-medium" href={`/politico/${row.personId}?ano=${row.year}`}>{row.ballotName || row.name}</Link><p>{row.name}</p><p>{row.office} · {row.party}/{row.state} · {row.year}</p><p>{row.municipality} · {row.result || "Resultado não informado"}</p><Link href={`/comparar?ids=${row.personId}&ano=${row.year}`} className="btn">Adicionar à comparação</Link><a className="source-link" href={`https://dadosabertos.tse.jus.br/pt_BR/dataset/candidatos-${row.year}`} target="_blank" rel="noopener noreferrer">Fonte oficial TSE</a></article>)}</div>{result.page>1&&<Link className="btn" href={`/explorar?${previous}`}>Página anterior</Link>}{result.page*24<result.total && <Link className="btn" href={`/explorar?${next}`}>Próxima página</Link>}{!result.total && <p>Nenhuma candidatura encontrada com esses filtros.</p>}</main>;
}
