import {createHash} from "node:crypto";
import {db,hasTable} from "@/lib/db";
import {normalizeName} from "@/lib/normalize";
import {platformStore,rateLimit} from "@/lib/platform/store";
export const dynamic="force-dynamic";
function fingerprint(input:string){let url:URL;try{url=new URL(input,"https://politica007.com.br");}catch{return null;}if(url.origin!=="https://politica007.com.br")return null;const person=/^\/politico\/(\d+)$/.exec(url.pathname),company=/^\/cnpj\/(\d{14})$/.exec(url.pathname);const digest=createHash("sha256");
 if(person){const id=Number(person[1]),selectedYear=Number(url.searchParams.get("ano"))||0;if(!Number.isSafeInteger(id))return null;const queries=["SELECT canonical_name,cpf FROM people WHERE id=?","SELECT year,round,office,party_abbr,state,municipality,candidacy_status,result FROM politician_history WHERE person_id=? ORDER BY year,round,tse_candidacy_id","SELECT d.year,d.tse_receipt_id,d.donor_cpf_cnpj,d.amount_cents FROM campaign_donation d JOIN campaign_org co ON co.id=d.campaign_org_id WHERE co.person_id=? ORDER BY d.year,d.tse_receipt_id","SELECT e.year,e.tse_expense_id,e.supplier_cpf_cnpj,e.amount_cents FROM campaign_expense e JOIN campaign_org co ON co.id=e.campaign_org_id WHERE co.person_id=? ORDER BY e.year,e.tse_expense_id","SELECT year,asset_type,description,value_cents FROM declared_assets WHERE person_id=? ORDER BY year,asset_type,description,value_cents"];for(let sql of queries){let args:number[]=[id];if(selectedYear&&!sql.startsWith("SELECT canonical_name")){const field=sql.includes("campaign_donation")?"d.year":sql.includes("campaign_expense")?"e.year":"year";sql=sql.replace(" ORDER BY",` AND ${field}=? ORDER BY`);args=[id,selectedYear];}for(const row of db().prepare(sql).iterate(...args))digest.update(JSON.stringify(row));}
 for(const table of ["electoral_case_candidate","election_vote_section"]){if(!hasTable(table))continue;const sql=table==="electoral_case_candidate"?"SELECT c.case_number,c.closed_at,c.last_decision_at,c.last_decision_type,cc.pole FROM electoral_case_candidate cc JOIN electoral_case c ON c.id=cc.case_id WHERE cc.person_id=? ORDER BY c.case_number,cc.pole":"SELECT h.year,v.round,v.state,v.municipality_code,v.zone_number,v.section_number,v.votes FROM election_vote_section v JOIN politician_history h ON h.id=v.history_id WHERE h.person_id=? ORDER BY h.year,v.round,v.state,v.municipality_code,v.zone_number,v.section_number";for(const row of db().prepare(sql).iterate(id))digest.update(JSON.stringify(row));}
 for(const row of platformStore().prepare("SELECT id,title,event_date,payload FROM external_record WHERE entity_key=? AND source='TSE propostas' ORDER BY id").iterate(String(id)))digest.update(JSON.stringify(row));
 if(hasTable("company_partner"))for(const row of db().prepare("SELECT cp.partner_name,cp.partner_doc_masked,cp.role,cp.entry_date FROM company_partner cp JOIN people p ON p.canonical_name=normalize_public_name(cp.partner_name) WHERE p.id=? ORDER BY cp.cnpj,cp.partner_name,cp.entry_date").iterate(id))digest.update(JSON.stringify(row));
 }else if(company){const cnpj=company[1];for(const row of db().prepare("SELECT legal_name,kind FROM companies WHERE cnpj=?").iterate(cnpj))digest.update(JSON.stringify(row));if(hasTable("company_registry"))for(const row of db().prepare("SELECT * FROM company_registry WHERE cnpj=?").iterate(cnpj))digest.update(JSON.stringify(row));for(const row of db().prepare("SELECT year,tse_receipt_id,amount_cents,cnpj FROM campaign_donation WHERE donor_cpf_cnpj=? ORDER BY year,tse_receipt_id,cnpj").iterate(cnpj))digest.update(JSON.stringify(row));for(const row of db().prepare("SELECT cp.partner_name,cp.partner_doc_masked,cp.role,cp.entry_date FROM company_partner cp WHERE cnpj=? ORDER BY partner_name,entry_date").iterate(cnpj))digest.update(JSON.stringify(row));for(const row of db().prepare("SELECT year,tse_expense_id,amount_cents,cnpj FROM campaign_expense WHERE supplier_cpf_cnpj=? ORDER BY year,tse_expense_id,cnpj").iterate(cnpj))digest.update(JSON.stringify(row));for(const row of platformStore().prepare("SELECT id,title,event_date,json_extract(payload,'$.valorGlobal') AS value FROM external_record WHERE entity_key=? AND source='PNCP' ORDER BY id").iterate(cnpj))digest.update(JSON.stringify(row));
 }else if(url.pathname==="/comparar"){const ids=(url.searchParams.get("ids")||"").split(",").map(Number).filter(n=>Number.isSafeInteger(n)&&n>0).slice(0,4);if(!ids.length)return null;const year=url.searchParams.get("ano")||"";for(const id of ids){const item=fingerprint(`/politico/${id}?ano=${year}`);if(item)digest.update(item.fingerprint);}digest.update(year);
 }else if(url.pathname==="/explorar"){const year=Number(url.searchParams.get("ano"))||0,state=url.searchParams.get("uf")||"",city=url.searchParams.get("cidade")||"",office=url.searchParams.get("cargo")||"";const clauses=["(?=0 OR year=?)","(?='' OR state=?)","(?='' OR office=?)"];const args:(string|number)[]=[year,year,state,state,office,office];for(const token of normalizeName(city).split(" ").filter(Boolean)){clauses.push("instr(normalize_public_name(coalesce(municipality,electoral_unit,'')),?)>0");args.push(token);}for(const token of normalizeName(url.searchParams.get("q")||"").split(" ").filter(Boolean)){clauses.push("(instr(normalized_name,?)>0 OR instr(normalize_public_name(coalesce(ballot_name,'')),?)>0)");args.push(token,token);}for(const row of db().prepare(`SELECT person_id,year,office,state,municipality,party_abbr,result,candidacy_status FROM politician_history WHERE ${clauses.join(" AND ")} ORDER BY person_id,year,office`).iterate(...args))digest.update(JSON.stringify(row));}else return null;
 return {fingerprint:digest.digest("hex"),checkedAt:new Date().toISOString()};}
export async function POST(request:Request){if(!rateLimit(request,"follow-status",20))return Response.json({error:"Aguarde para verificar novamente."},{status:429});const b=await request.json().catch(()=>null);if(!b||!Array.isArray(b.paths)||b.paths.length>20||b.paths.some((p:unknown)=>typeof p!=="string"||p.length>1000))return Response.json({error:"Consulta inválida."},{status:400});return Response.json({items:b.paths.map((path:string)=>({path,...fingerprint(path)}))});}
