import Link from "next/link";
import {db,hasTable} from "@/lib/db";
import {normalizeName} from "@/lib/normalize";
import {PageHeader} from "@/components/shell/shell-context";
import {PaginationLinks} from "@/components/ui/pagination-links";
export const dynamic="force-dynamic";
const THEMES:Record<string,string[]>={saude:["SAUDE","HOSPITAL","SUS"],educacao:["EDUCACAO","ESCOLA","PROFESSOR"],seguranca:["SEGURANCA","POLICIA","VIOLENCIA"],economia:["ECONOMIA","EMPREGO","IMPOSTO"],ambiente:["AMBIENTE","CLIMA","FLORESTA"]};
export default async function Page({searchParams}:PageProps<"/redes">){
 const p=await searchParams,q=typeof p.q==="string"?p.q.slice(0,120):"",theme=typeof p.tema==="string"?p.tema:"",from=typeof p.de==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(p.de)?p.de:"",to=typeof p.ate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(p.ate)?p.ate:"",personId=Number(p.pessoa)||0,page=Math.max(1,Math.min(10000,Math.floor(Number(p.page)||1)));
 const clauses:string[]=[],args:(string|number)[]=[];
 for(const token of normalizeName(q).split(" ").filter(Boolean)){clauses.push("instr(normalize_public_name(sp.text||' '||coalesce(pe.canonical_name,'')||' '||a.handle),?)>0");args.push(token);}
 if(THEMES[theme]){clauses.push("("+THEMES[theme].map(()=>"instr(normalize_public_name(sp.text),?)>0").join(" OR ")+")");args.push(...THEMES[theme]);}
 if(from){clauses.push("substr(public_timestamp(sp.posted_at),1,10)>=?");args.push(from);}if(to){clauses.push("substr(public_timestamp(sp.posted_at),1,10)<=?");args.push(to);}if(personId){clauses.push("a.person_id=?");args.push(personId);}
 const where=clauses.length?"WHERE "+clauses.join(" AND "):"",joined="FROM social_post sp JOIN social_account a ON a.id=sp.social_account_id LEFT JOIN people pe ON pe.id=a.person_id";
 const available=hasTable("social_post"),total=available?(db().prepare(`SELECT count(*) AS n ${joined} ${where}`).get(...args) as {n:number}).n:0;
 const rows=available?db().prepare(`SELECT sp.id,sp.text,sp.kind,public_timestamp(sp.posted_at) AS postedAt,sp.retrieved_at AS collectedAt,sp.url,sp.in_reply_to_external AS replyTo,a.handle,a.person_id AS personId,pe.canonical_name AS name ${joined} ${where} ORDER BY public_timestamp(sp.posted_at) DESC,sp.id DESC LIMIT 20 OFFSET ?`).all(...args,(page-1)*20) as {id:number;text:string;kind:string;postedAt:string|null;collectedAt:string;url:string|null;replyTo:string|null;handle:string;personId:number|null;name:string|null}[]:[];
 const href=(next:number)=>{const params=new URLSearchParams();for(const [key,value] of [["q",q],["tema",theme],["de",from],["ate",to],["pessoa",personId?String(personId):""]])if(value)params.set(key,value);params.set("page",String(next));return `/redes?${params}`;};
 return <main className="platform-page"><PageHeader group="Consulta" current="Publicações e temas"/><h1>Publicações públicas e temas</h1><p>Texto coletado de contas declaradas ao TSE. Não representa todas as publicações, nem comprova uma posição permanente. Temas são filtros por palavras, podem incluir citações ou críticas. Consulte o contexto original.</p><form className="platform-form" action="/redes"><label>Nome, perfil ou trecho<input name="q" defaultValue={q}/></label><label>Tema<select name="tema" defaultValue={theme}><option value="">Todos</option>{Object.keys(THEMES).map(t=><option key={t} value={t}>{({saude:"Saúde",educacao:"Educação",seguranca:"Segurança",economia:"Economia",ambiente:"Meio ambiente"} as Record<string,string>)[t]}</option>)}</select></label><label>De<input type="date" name="de" defaultValue={from}/></label><label>Até<input type="date" name="ate" defaultValue={to}/></label>{personId>0&&<input type="hidden" name="pessoa" value={personId}/>}<button className="btn">Pesquisar em toda a coleta</button></form><p>{total.toLocaleString("pt-BR")} publicações encontradas</p><div className="platform-grid">{rows.map(r=><article className="card" key={r.id}><h2>{r.personId?<Link className="link-primary" href={`/politico/${r.personId}`}>{r.name||r.handle}</Link>:r.name||r.handle}</h2><p>@{r.handle} · {r.kind==="reply"?"Resposta":r.kind==="quote"?"Citação":"Publicação"} · {r.postedAt?new Date(r.postedAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"}):"Data não informada"}</p><p className="my-3 whitespace-pre-wrap">{r.text}</p>{r.replyTo&&<p className="text-xs">Este texto é parte de uma conversa; leia a mensagem anterior na fonte para avaliar o contexto.</p>}{r.url&&<a href={r.url} target="_blank" rel="noopener noreferrer" className="source-link" data-source-date={r.collectedAt}>Fonte original e contexto</a>}<p className="text-xs">Coletado em {new Date(r.collectedAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</p></article>)}</div>{!rows.length&&<p>Nenhuma publicação encontrada na coleta disponível. Isso não indica ausência de publicações ou de posicionamento.</p>}<PaginationLinks page={page} totalPages={Math.max(1,Math.ceil(total/20))} makeHref={href}/></main>;
}
