"use client";
import {useState} from "react";
import type {OfficialPage} from "@/lib/platform/official";
export function OfficialRecords({personId}:{personId:number}){
 const [month,setMonth]=useState(new Date().getMonth()+1);
 const [kind,setKind]=useState("proposicoes"),[year,setYear]=useState(new Date().getFullYear()),[data,setData]=useState<OfficialPage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(page=1){setBusy(true);setError("");try{const r=await fetch(`/api/platform?personId=${personId}&kind=${kind}&ano=${year}&mes=${month}&page=${page}`);const d=await r.json();if(!r.ok)throw Error(d.error);setData(prior=>page>1&&prior?{...d,items:[...prior.items,...d.items]}:d);}catch(e){setError(e instanceof Error?e.message:"Falha ao consultar.");}finally{setBusy(false);}}
 return <section id="atividade-legislativa" data-toc-title="Atividade parlamentar" className="py-7"><h2 className="section-title mb-3">Atividade parlamentar · Câmara e Senado</h2><p className="text-sm mb-3">Consulte projetos, despesas parlamentares e votos nominais na Câmara e no Senado. Cada fonte informa o critério de associação e a cobertura; coincidências parciais aparecem como possíveis correspondências.</p><div className="platform-form"><label>Registros<select value={kind} onChange={e=>{setKind(e.target.value);setData(null);}}><option value="proposicoes">Projetos e proposições</option><option value="camara-votos">Votações na Câmara</option><option value="senado-votos">Votações nominais no Senado</option><option value="despesas">Despesas da cota parlamentar</option></select></label><label>Ano<input type="number" min="1994" max="2100" value={year} onChange={e=>{setYear(Number(e.target.value));setData(null);}}/></label>{kind==="camara-votos"&&<label>Mês<select value={month} onChange={e=>{setMonth(Number(e.target.value));setData(null);}}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>}<button className="btn" disabled={busy} onClick={()=>load()}>{busy?"Consultando fonte…":"Consultar registros"}</button></div>{error&&<p role="alert">{error}</p>}{data&&<><p className="text-sm my-3">{data.identity} · {data.coverage}</p><div className="platform-grid">{data.items.map((r,i)=><article className="card" key={`${r.id}-${i}`}><h3>{r.title}</h3><p>{r.date}</p><p>{r.detail}</p><a className="source-link" href={r.url} target="_blank" rel="noopener noreferrer">Registro oficial</a></article>)}</div>{data.hasMore&&<button disabled={busy} className="btn" onClick={()=>load(data.page+1)}>Veja mais</button>}<a href={data.sourceUrl} className="source-link" target="_blank" rel="noopener noreferrer">Fonte da consulta · {new Date(data.collectedAt).toLocaleString("pt-BR")}</a></>}</section>;
}
