"use client";
import {useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import Link from "next/link";
import {GraphShareButton} from "@/components/graph/graph-share-button";
export type SavedPage={url:string;title:string;savedAt:string};
export const SAVED_KEY="politica007:saved:v1";
export function readSaved():SavedPage[]{try{const value=JSON.parse(localStorage.getItem(SAVED_KEY)||"[]");return Array.isArray(value)?value.filter(p=>p&&typeof p.url==="string"&&p.url.startsWith("/")&&!p.url.startsWith("//")&&typeof p.title==="string"&&typeof p.savedAt==="string"):[];}catch{return [];}}
async function updateFollowed(pages:SavedPage[]){
 const before=JSON.parse(localStorage.getItem("politica:follow-baselines")||"{}") as Record<string,string>;
 const found=new Set<string>(JSON.parse(localStorage.getItem("politica:follow-changes")||"[]"));
 for(let i=0;i<pages.length;i+=20){const response=await fetch("/api/platform-status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paths:pages.slice(i,i+20).map(p=>p.url)})});if(!response.ok)throw Error();const data=await response.json() as {items:{path:string;fingerprint?:string}[]};for(const item of data.items){if(!item.fingerprint)continue;if(before[item.path]&&before[item.path]!==item.fingerprint)found.add(item.path);before[item.path]=item.fingerprint;}}
 const paths=[...found].filter(path=>pages.some(p=>p.url===path));localStorage.setItem("politica:follow-baselines",JSON.stringify(before));localStorage.setItem("politica:follow-changes",JSON.stringify(paths));localStorage.setItem("politica:follow-check",String(Date.now()));window.dispatchEvent(new Event("politica-follow-checked"));return paths;
}
export function PageTools(){
 const [updates,setUpdates]=useState(0);const [storageError,setStorageError]=useState("");
 const pathname=usePathname();const target=useRef<HTMLElement|null>(null);const [saved,setSaved]=useState(false);const [title,setTitle]=useState("Dados públicos");
 useEffect(()=>{target.current=document.querySelector(".content__inner main")||document.querySelector(".graph-page-body")||document.querySelector(".content__inner");const timer=setTimeout(()=>{setTitle(document.querySelector("h1")?.textContent||"Dados públicos");setSaved(readSaved().some(p=>p.url===location.pathname+location.search));},200);return ()=>clearTimeout(timer);},[pathname]);
 useEffect(()=>{let running=false;const refresh=()=>{try{setUpdates(JSON.parse(localStorage.getItem("politica:follow-changes")||"[]").length);}catch{}};const check=async()=>{if(running||document.visibilityState!=="visible")return;try{const last=Number(localStorage.getItem("politica:follow-check")||0);if(Date.now()-last<4*3600000)return;running=true;const pages=readSaved();if(pages.length)await updateFollowed(pages);}catch{}finally{running=false;refresh();}};refresh();check();const timer=setInterval(check,60000);window.addEventListener("politica-follow-checked",refresh);document.addEventListener("visibilitychange",check);return()=>{clearInterval(timer);window.removeEventListener("politica-follow-checked",refresh);document.removeEventListener("visibilitychange",check);};},[]);
 function save(){try{const url=location.pathname+location.search;const pages=readSaved();const exists=pages.some(p=>p.url===url);localStorage.setItem(SAVED_KEY,JSON.stringify(exists?pages.filter(p=>p.url!==url):[...pages,{url,title,savedAt:new Date().toISOString()}]));setSaved(!exists);window.dispatchEvent(new Event("politica-saved"));setStorageError("");}catch{setStorageError("O navegador não permitiu salvar esta consulta. Verifique o armazenamento local.");}}
 return <div className="platform-toolbar" data-graph-share-ignore><button className="btn" aria-pressed={saved} onClick={save}>{saved?"★ Acompanhando":"☆ Acompanhar esta consulta"}</button><GraphShareButton targetRef={target} title={title}/><Link className="btn" href="/acompanhar">Minhas consultas{updates?` · ${updates} com novidades`:""}</Link>{storageError&&<p role="alert">{storageError}</p>}</div>;
}
export function SavedPages(){
 const[pages,setPages]=useState<SavedPage[]>([]),[changes,setChanges]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const refresh=()=>{setPages(readSaved());try{setChanges(JSON.parse(localStorage.getItem("politica:follow-changes")||"[]"));}catch{}};refresh();window.addEventListener("politica-saved",refresh);return()=>window.removeEventListener("politica-saved",refresh);},[]);
 async function check(){setBusy(true);try{const found=await updateFollowed(pages);setChanges(found);setMessage(found.length?`${found.length} consultas com alterações nos dados acompanhados.`:"Verificação concluída. Sem alterações desde a referência salva; na primeira verificação, a referência é criada.");}catch{setMessage("Não foi possível verificar todas as consultas. Tente novamente.");}finally{setBusy(false);}}
 return <><p>Consultas, perfis, regiões e comparações salvos neste navegador. O link preserva os filtros da consulta. Verifique mudanças em candidaturas, finanças, patrimônio, quadro societário e contratos coletados. A verificação acontece automaticamente a cada quatro horas enquanto o portal está aberto, e pode ser antecipada pelo botão. Mudanças ficam destacadas aqui; não há notificações com o navegador fechado.</p><button className="btn" disabled={busy} onClick={check}>{busy?"Verificando…":"Verificar novidades nas consultas"}</button><p role="status">{message}</p>{changes.length>0&&<button className="btn" onClick={()=>{localStorage.setItem("politica:follow-changes","[]");setChanges([]);window.dispatchEvent(new Event("politica-follow-checked"));}}>Marcar novidades como lidas</button>}<div className="platform-grid">{pages.map(p=><article className="card" key={p.url}>{changes.includes(p.url)&&<strong>Dados atualizados desde a última verificação</strong>}<Link className="link-primary" href={p.url}>{p.title}</Link><p className="text-sm mt-2">Salvo em {new Date(p.savedAt).toLocaleDateString("pt-BR")}</p><button className="btn mt-3" onClick={()=>{localStorage.setItem(SAVED_KEY,JSON.stringify(pages.filter(x=>x.url!==p.url)));window.dispatchEvent(new Event("politica-saved"));}}>Remover</button></article>)}</div>{!pages.length&&<p>Abra um perfil ou consulta e toque em “Acompanhar esta consulta”.</p>}</>;
}
