import Link from "next/link";
import {getPersonCandidacies,getPersonAssets} from "@/lib/queries";
import {getCachedPersonFinance} from "@/lib/platform/person-finance";
import {formatBRL} from "@/lib/format";
export function ProfileNavigation(){return <nav className="platform-tabs" aria-label="Seções do perfil">{[["candidaturas","Histórico"],["votos-por-local","Votos"],["financas","Finanças"],["empresas-relacionadas","Empresas"],["processos-eleitorais","Processos"],["bens-declarados","Patrimônio"],["atividade-legislativa","Atividade parlamentar"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>;}
export async function ProfileTimeline({personId}:{personId:number}){await new Promise<void>(resolve=>setTimeout(resolve,0));const candidacies=getPersonCandidacies(personId),assets=getPersonAssets(personId).declaredAssetsByYear;return <details className="card my-4" id="linha-do-tempo" data-toc-title="Linha do tempo"><summary>Linha do tempo eleitoral e patrimonial</summary><ol className="mt-4 flex flex-col gap-4">{candidacies.map(c=>{const a=assets.find(a=>a.year===c.year);return <li key={c.id}><strong>{c.year} · {c.office} · {c.partyAbbr}/{c.state}</strong><p>{c.result||"Resultado ainda não informado"} · {a?(a.missingValues===a.count?"Patrimônio com valores não informados":`Patrimônio declarado: ${formatBRL(a.totalCents)}${a.missingValues?" (soma dos valores informados)":""}`):"Patrimônio sem declaração coletada para esta eleição"}</p><a className="source-link" href={c.provenance.url} target="_blank" rel="noopener noreferrer">Arquivo oficial desta candidatura</a></li>;})}</ol></details>;}
export async function FinanceInsights({personId,year}:{personId:number;year?:number}){
 await new Promise<void>(resolve=>setTimeout(resolve,0));
 const finance=await getCachedPersonFinance(personId,year);
 const {suppliers,donationOrigins:origins,expenseYears:years}=finance;
 const total=finance.expensesTotalCents,top=suppliers.slice(0,5),share=total?top.reduce((n,r)=>n+r.cents,0)/total*100:0;
 return <section className="py-7" id="resumo-financeiro" data-toc-title="Concentração e evolução"><h2 className="section-title">Concentração de fornecedores e origem dos recursos</h2><p className="text-sm my-3">{year?`Eleição ${year}`:"Todas as eleições coletadas"}. {total>0?`Os cinco maiores fornecedores concentram ${share.toFixed(1).replace(".",",")}% das despesas contratadas.`:"Concentração não calculável: não há valores positivos de despesas neste recorte."} Concentração não demonstra irregularidade.</p><div className="platform-grid"><article className="card"><h3>Maiores fornecedores · contratado</h3>{top.map((r,i)=><p key={i} className="my-3">{r.doc?<Link className="link-primary" href={`/${r.doc.length===14?"cnpj":"cpf"}/${r.doc}`}>{r.name||r.doc}</Link>:r.name||"Fornecedor sem documento"}<br/>{formatBRL(r.cents)} · {total?(r.cents/total*100).toFixed(1):"0"}%</p>)}</article><article className="card"><h3>Origem das doações recebidas</h3>{origins.map(r=><p className="my-3" key={r.name}>{r.name}<br/>{formatBRL(r.cents)}</p>)}</article><article className="card"><h3>Despesas por eleição</h3>{years.map(r=><p className="my-3" key={r.year}><Link href={`/politico/${personId}?ano=${r.year}`} className="link-primary">{r.year}</Link> · {formatBRL(r.cents)}<br/>{r.n.toLocaleString("pt-BR")} registros</p>)}</article></div><a className="source-link" href={`https://dadosabertos.tse.jus.br/pt_BR/dataset/prestacao-de-contas-eleitorais-${year||years.at(-1)?.year||2026}`} target="_blank" rel="noopener noreferrer">Fonte oficial · prestações de contas do TSE</a></section>;
}
